extends Node
class_name TestRunner

const COLOR_SUCCESS := "#22c55e"
const COLOR_ERROR := "#ef4444"
const COLOR_INFO := "#3b82f6"
const COLOR_DEBUG := "#9ca3af"

const INDEX_FILE := "res://tests/index.gd"
const TESTS_DIR := "res://tests"

var log_label: RichTextLabel
var indent_level: int = 0
var total_passed: int = 0
var total_failed: int = 0
var is_headless := false
var tests_complete := false

static var ctx := TestContext.new()


class TestContext:
	var runner: TestRunner = null
	var current_test: String = ""

	func log_info(msg: String) -> void:
		if runner:
			runner._log("[%s] %s" % [current_test, msg], COLOR_INFO)

	func log_debug(msg: String) -> void:
		if runner:
			runner._log("[%s] %s" % [current_test, msg], COLOR_DEBUG)

	func log_error(msg: String) -> void:
		if runner:
			runner._log("[%s] %s" % [current_test, msg], COLOR_ERROR)


func _ready() -> void:
	is_headless = DisplayServer.get_name() == "headless"

	if not is_headless:
		log_label = $ScrollContainer/LogLabel
		log_label.text = ""

	ctx.runner = self

	# Set up a timeout failsafe in case tests get stuck
	var timeout_ms := 60000
	var timeout_str := OS.get_environment("GODOT_TEST_RUNNER_TIMEOUT")
	if timeout_str != "":
		timeout_ms = int(timeout_str)

	get_tree().create_timer(timeout_ms / 1000.0).timeout.connect(_on_timeout)

	log_info("Starting test session")
	indent_level += 1

	# Try to regenerate the test index on each run (only possible in editor/dev builds)
	_try_regenerate_test_index()

	var test_files := _get_test_files()
	if test_files.is_empty():
		log_error("No test suites found")
		tests_complete = true
		_quit_tests_now(1)
		return

	for file in test_files:
		_run_suite(file)

	indent_level -= 1
	log_info("==============================")

	if total_failed > 0:
		log_error("FAILED: %d passed, %d failed" % [total_passed, total_failed])
	else:
		log_success("PASSED: %d tests total" % total_passed)

	tests_complete = true
	_quit_tests_now(1 if total_failed > 0 else 0)


func _try_regenerate_test_index() -> void:
	# Try to regenerate the index in development builds
	var dir := DirAccess.open(TESTS_DIR)
	if dir == null:
		# Cannot access filesystem - likely running an exported binary
		return

	var test_files: Array[String] = []
	dir.list_dir_begin()
	var fname := dir.get_next()
	while fname != "":
		if not dir.current_is_dir() and fname.begins_with("test_") and fname.ends_with(".gd"):
			test_files.append(fname)
		fname = dir.get_next()
	dir.list_dir_end()

	if test_files.is_empty():
		# No tests found, create empty index
		_write_test_index([])
		return

	test_files.sort()
	_write_test_index(test_files)


func _write_test_index(test_files: Array[String]) -> void:
	var header := """# WARNING: This file is auto-generated by TestRunner._write_test_index()
# Do not edit manually. Changes will be overwritten on each test run.
# This file is necessary for test runner compatibility with exported binaries.

"""
	var content := header

	content += "const SUITES := [\n"
	for fname in test_files:
		content += "\t\"res://tests/%s\",\n" % fname
	content += "]\n"

	var file := FileAccess.open(INDEX_FILE, FileAccess.WRITE)
	if file == null:
		log_debug("Note: Could not regenerate test index (expected in exported builds)")
		return

	file.store_string(content)


func _get_test_files() -> Array[String]:
	# First, try to load the index file (works in both editor and exported builds)
	var index = load(INDEX_FILE)
	if index != null:
		# Try to get SUITES constant from the loaded script
		var suites: Array = []
		if "SUITES" in index:
			suites = index.SUITES
		else:
			# Try to get it as a constant
			var constants = index.get_script_constant_map()
			if "SUITES" in constants:
				suites = constants["SUITES"]

		if not suites.is_empty():
			var files: Array[String] = []
			for suite_path in suites:
				if suite_path is String:
					files.append(suite_path.get_file())
			if not files.is_empty():
				return files

	# Fallback: Try to discover test files dynamically (only works in editor)
	var dir := DirAccess.open(TESTS_DIR)
	if dir == null:
		return []

	var test_files: Array[String] = []
	dir.list_dir_begin()
	var fname := dir.get_next()
	while fname != "":
		if not dir.current_is_dir() and fname.begins_with("test_") and fname.ends_with(".gd"):
			test_files.append(fname)
		fname = dir.get_next()
	dir.list_dir_end()
	test_files.sort()
	return test_files


func _on_timeout() -> void:
	if not tests_complete:
		log_error("Test runner timeout after GODOT_TEST_RUNNER_TIMEOUT seconds")
		get_tree().quit(1)


func _run_suite(file: String) -> void:
	var path := "res://tests/" + file
	var script := load(path)

	if script == null:
		log_error("Failed to load: %s" % path)
		total_failed += 1
		return

	var methods: Array[String] = []
	for m in script.get_script_method_list():
		if m["name"].begins_with("test_"):
			methods.append(m["name"])

	methods.sort()
	if methods.is_empty():
		return

	var suite_name := file.trim_suffix(".gd")
	log_info("Suite: %s" % suite_name)
	indent_level += 1

	var suite_passed := 0
	var suite_failed := 0
	var suite_start := Time.get_ticks_usec()

	for method in methods:
		ctx.current_test = "%s.%s" % [suite_name, method]

		var start := Time.get_ticks_usec()
		var result := _run_test(script, method)
		var duration_ms := (Time.get_ticks_usec() - start) / 1000.0

		if result == "":
			log_success("✓ %s (%.3f ms)" % [method, duration_ms])
			suite_passed += 1
		else:
			log_error("✗ %s: %s (%.3f ms)" % [method, result, duration_ms])
			suite_failed += 1

			var stack = get_stack()
			for frame in stack:
				if frame is Dictionary and frame.get("source", "").begins_with("res://tests"):
					log_debug("  at %s:%d" % [frame.get("source", "?"), frame.get("line", 0)])

	var suite_duration_ms := (Time.get_ticks_usec() - suite_start) / 1000.0

	indent_level -= 1
	log_info("Suite result: %s [%d/%d] (%.3f ms)" %
		[suite_name, suite_passed, suite_passed + suite_failed, suite_duration_ms])

	total_passed += suite_passed
	total_failed += suite_failed


func _run_test(script: Object, method: String) -> String:
	if not script.has_method(method):
		return "Method not found"

	var result = script.call(method)

	if result == null:
		return ""

	if typeof(result) != TYPE_STRING:
		return "Invalid return type: expected String"

	return result


func log_success(message: String) -> void:
	_log(message, COLOR_SUCCESS)

func log_error(message: String) -> void:
	_log(message, COLOR_ERROR)

func log_info(message: String) -> void:
	_log(message, COLOR_INFO)

func log_debug(message: String) -> void:
	_log(message, COLOR_DEBUG)


func _log(message: String, color: String) -> void:
	var indent := "  ".repeat(indent_level)
	var formatted := "[color=%s]%s%s[/color]" % [color, indent, message]

	print_rich(formatted)

	if not is_headless and log_label:
		log_label.text += ("\n" if log_label.text != "" else "") + formatted

		var sc := log_label.get_parent()
		if sc is ScrollContainer:
			# WARNING: Using await here only for GUI updates to avoid Godot engine bugs
			# on Windows unrelated to this GDExtension. All other code is kept sequential
			# to prevent Windows-specific event loop issues that cause test runner hangs.
			await get_tree().process_frame
			sc.scroll_vertical = int(sc.get_v_scroll_bar().max_value)


# WARNING: This function is kept completely sequential (no async/await) to avoid
# Windows-only bugs in Godot's event loop and process frame handling that are
# unrelated to this GDExtension. Any await statements outside of _log() will cause
# the test runner to hang indefinitely on Windows, even though the same code works
# on Linux and macOS. The shutdown must be immediate and synchronous.
func _quit_tests_now(code: int) -> void:
	# Always quit when running in test mode or headless
	var env_test_runner := OS.get_environment("GODOT_TEST_RUNNER") == "true"
	var is_headless_mode := DisplayServer.get_name() == "headless"
	var should_quit := env_test_runner or is_headless_mode or code != 0

	if should_quit:
		get_tree().quit(code)
