#!/bin/bash
#
# register_types.sh - Generator for register_types.cpp and register_types.h
#
# This script scans the directory recursively for GDCLASS definitions and
# generates the corresponding registration code.
#

set -e

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Output files
HEADER_FILE="$SCRIPT_DIR/register_types.h"
CPP_FILE="$SCRIPT_DIR/register_types.cpp"

# Temporary files for collecting class names and inheritance pairs
CLASSES_FILE=$(mktemp)
CLASS_PAIRS_FILE=$(mktemp)
trap "rm -f $CLASSES_FILE $CLASS_PAIRS_FILE" EXIT

# Find all GDCLASS definitions recursively
echo "Scanning for GDCLASS definitions..."

# Search for GDCLASS patterns in header files (excluding godot-cpp and vcpkg)
grep -r "GDCLASS\s*(" "$SCRIPT_DIR" \
    --include="*.h" \
    --include="*.hpp" \
    --exclude-dir="godot-cpp" \
    --exclude-dir="vcpkg" 2>/dev/null | \
    sed -E 's/.*GDCLASS\s*\(\s*([A-Za-z_][A-Za-z0-9_]*)\s*,\s*([A-Za-z_:][A-Za-z0-9_:]*)\s*\).*/\1|\2/' | \
    sort | uniq > "$CLASS_PAIRS_FILE"

declare -A CLASS_PARENTS
declare -A REMAINING
CLASSES=()

while IFS='|' read -r classname parentname; do
    [ -z "$classname" ] && continue
    CLASSES+=("$classname")
    CLASS_PARENTS["$classname"]="$parentname"
    REMAINING["$classname"]=1
done < "$CLASS_PAIRS_FILE"

> "$CLASSES_FILE"
SORTED_COUNT=0

while [ "$SORTED_COUNT" -lt "${#CLASSES[@]}" ]; do
    PROGRESSED=0
    for classname in "${CLASSES[@]}"; do
        [ -z "${REMAINING[$classname]}" ] && continue

        parentname="${CLASS_PARENTS[$classname]}"
        if [ -z "${REMAINING[$parentname]}" ]; then
            echo "$classname" >> "$CLASSES_FILE"
            unset REMAINING["$classname"]
            SORTED_COUNT=$((SORTED_COUNT + 1))
            PROGRESSED=1
        fi
    done

    if [ "$PROGRESSED" -eq 0 ]; then
        for classname in "${CLASSES[@]}"; do
            [ -z "${REMAINING[$classname]}" ] && continue
            echo "$classname" >> "$CLASSES_FILE"
            unset REMAINING["$classname"]
            SORTED_COUNT=$((SORTED_COUNT + 1))
        done
    fi
done

# Count found classes
CLASS_COUNT=$(wc -l < "$CLASSES_FILE")

if [ "$CLASS_COUNT" -eq 0 ] || [ ! -s "$CLASSES_FILE" ]; then
    echo "Warning: No GDCLASS definitions found!"
else
    echo "Found $CLASS_COUNT class(es):"
    sed 's/^/  - /' "$CLASSES_FILE"
fi

# Generate register_types.h
echo ""
echo "Generating $HEADER_FILE..."
cat > "$HEADER_FILE" << 'EOF'
// register_types.h - Header for class registration
// This file is auto-generated by register_types.sh. Do not edit manually.

#ifndef REGISTER_TYPES_H
#define REGISTER_TYPES_H

#include "gdextension_interface.h"
#include <godot_cpp/core/class_db.hpp>
#include <godot_cpp/godot.hpp>
#include <godot_cpp/core/defs.hpp>

void gdext_initialize_module(godot::ModuleInitializationLevel p_level);

void gdext_uninitialize_module(godot::ModuleInitializationLevel p_level);

extern "C" {
    auto GDE_EXPORT gdext_library_init(
        GDExtensionInterfaceGetProcAddress p_get_proc_address,
        GDExtensionClassLibraryPtr p_library,
        GDExtensionInitialization *r_initialization
    ) -> GDExtensionBool;
}

#endif // REGISTER_TYPES_H
EOF

# Generate register_types.cpp
echo "Generating $CPP_FILE..."

# Start building the CPP file
{
    cat << 'EOF'
// register_types.cpp - Implementation for class registration
// This file is auto-generated by register_types.sh. Do not edit manually.

#include "register_types.h"

// Include headers for all detected classes
EOF

    # Find and include all header files that contain GDCLASS definitions
    grep -r "GDCLASS\s*(" "$SCRIPT_DIR" \
        --include="*.h" \
        --include="*.hpp" \
        --exclude-dir="godot-cpp" \
        --exclude-dir="vcpkg" 2>/dev/null | \
        cut -d: -f1 | \
        sort | uniq | \
        sed "s|$SCRIPT_DIR/||" | \
        sed 's/^/#include "/' | \
        sed 's/$/"/'

    cat << 'EOF'
// OCCT fix: Godot corrupts std::cout's vtable during startup and shutdown.
// Null the private myStream pointer so Message_PrinterOStream::Close() is safe.
#include <Message.hxx>
#include <Message_Messenger.hxx>
#include <Message_PrinterOStream.hxx>

static void clear_messenger_printers() {
    Handle(Message_Messenger) const messenger = Message::DefaultMessenger();
    if (messenger.IsNull()) {
        return;
    }

    const Message_SequenceOfPrinters& printers = messenger->Printers();
    for (int i = 1; i <= printers.Size(); i++) {
        Handle(Message_PrinterOStream) const osp =
            Handle(Message_PrinterOStream)::DownCast(printers.Value(i));
        if (!osp.IsNull()) {
            // Nulify the private myStream field so Close() returns immediately.
            // Layout: vtable(8) + refcount(4) + myTraceLevel(4) + myStream(8) ...
            *reinterpret_cast<void**>(reinterpret_cast<char*>(osp.get()) + 16) = nullptr;
        }
    }

    messenger->ChangePrinters().Clear();
}

void gdext_initialize_module(godot::ModuleInitializationLevel p_level) {
    if (p_level != godot::MODULE_INITIALIZATION_LEVEL_SCENE) {
        return;
    }

    // Register all discovered wrapper classes
EOF

    # Add GDREGISTER_CLASS calls for each class
    while IFS= read -r classname; do
        if [ -n "$classname" ]; then
            echo "    GDREGISTER_CLASS($classname);"
        fi
    done < "$CLASSES_FILE"

    cat << 'EOF'
    clear_messenger_printers();
}

void gdext_uninitialize_module(godot::ModuleInitializationLevel p_level) {
    if (p_level != godot::MODULE_INITIALIZATION_LEVEL_SCENE) {
        return;
    }
    clear_messenger_printers();
}

extern "C" {
    auto GDE_EXPORT gdext_library_init(
        GDExtensionInterfaceGetProcAddress p_get_proc_address,
        GDExtensionClassLibraryPtr p_library,
        GDExtensionInitialization *r_initialization
    ) -> GDExtensionBool {
        godot::GDExtensionBinding::InitObject const init_obj(
            p_get_proc_address, p_library, r_initialization
        );

        init_obj.register_initializer(gdext_initialize_module);
        init_obj.register_terminator(gdext_uninitialize_module);
        init_obj.set_minimum_library_initialization_level(godot::MODULE_INITIALIZATION_LEVEL_SCENE);

        return init_obj.init();
    }
}
EOF
} > "$CPP_FILE"

echo "Done!"
echo ""
echo "Summary:"
echo "  - Header: $HEADER_FILE"
echo "  - Implementation: $CPP_FILE"
