// register_types.cpp - Implementation for class registration
// This file is auto-generated by register_types.sh. Do not edit manually.

#include "register_types.h"

#include <godot_cpp/godot.hpp>
#include <godot_cpp/core/defs.hpp>

#include "gdextension_interface.h"

// Include headers for all detected classes
#include "Axis.h"
#include "Edge.h"
#include "Face.h"
#include "GeometryVector.h"
#include "Location.h"
#include "OpenCascadeVersion.h"
#include "Solid.h"
#include "SolidBox.h"
#include "SolidCone.h"
#include "SolidCylinder.h"
#include "SolidSphere.h"
#include "TopoShape.h"
#include "Vertex.h"
#include "Wire.h"

using namespace godot;

void gdext_initialize_module(ModuleInitializationLevel p_level) {
    if (p_level != MODULE_INITIALIZATION_LEVEL_SCENE) {
        return;
    }

    // Register all discovered wrapper classes
    GDREGISTER_CLASS(Axis);
    GDREGISTER_CLASS(GeometryVector);
    GDREGISTER_CLASS(Location);
    GDREGISTER_CLASS(OpenCascadeVersion);
    GDREGISTER_CLASS(TopoShape);
    GDREGISTER_CLASS(Vertex);
    GDREGISTER_CLASS(Wire);
    GDREGISTER_CLASS(Edge);
    GDREGISTER_CLASS(Face);
    GDREGISTER_CLASS(Solid);
    GDREGISTER_CLASS(SolidBox);
    GDREGISTER_CLASS(SolidCone);
    GDREGISTER_CLASS(SolidCylinder);
    GDREGISTER_CLASS(SolidSphere);
}

void gdext_uninitialize_module(ModuleInitializationLevel p_level) {
    (void)p_level;
    // Teardown logic (if any) goes here.
}

extern "C" {
    auto GDE_EXPORT gdext_library_init(
        GDExtensionInterfaceGetProcAddress p_get_proc_address,
        GDExtensionClassLibraryPtr p_library,
        GDExtensionInitialization *r_initialization
    ) -> GDExtensionBool {
        godot::GDExtensionBinding::InitObject const init_obj(
            p_get_proc_address, p_library, r_initialization
        );

        init_obj.register_initializer(gdext_initialize_module);
        init_obj.register_terminator(gdext_uninitialize_module);
        init_obj.set_minimum_library_initialization_level(MODULE_INITIALIZATION_LEVEL_SCENE);

        return init_obj.init();
    }
}
