// register_types.cpp - Implementation for class registration
// This file is auto-generated by register_types.sh. Do not edit manually.

#include "register_types.h"

// Include headers for all detected classes
#include "Axis.h"
#include "CircleWire.h"
#include "Compound.h"
#include "Edge.h"
#include "EllipseWire.h"
#include "Face.h"
#include "GeometryVector.h"
#include "Location.h"
#include "OpenCascadeVersion.h"
#include "Plane.h"
#include "PolygonWire.h"
#include "RectangleRoundedWire.h"
#include "RectangleWire.h"
#include "RegularPolygonWire.h"
#include "ShapeList.h"
#include "Shell.h"
#include "SlotOverallWire.h"
#include "SolidBox.h"
#include "SolidCone.h"
#include "SolidCylinder.h"
#include "Solid.h"
#include "SolidSphere.h"
#include "SolidTorus.h"
#include "SolidWedge.h"
#include "TopoShape.h"
#include "Vertex.h"
#include "Wire.h"
// OCCT fix: Godot corrupts std::cout's vtable during startup and shutdown.
// Null the private myStream pointer so Message_PrinterOStream::Close() is safe.
#include <Message.hxx>
#include <Message_Messenger.hxx>
#include <Message_PrinterOStream.hxx>

static void clear_messenger_printers() {
    Handle(Message_Messenger) const messenger = Message::DefaultMessenger();
    if (messenger.IsNull()) {
        return;
    }

    const Message_SequenceOfPrinters& printers = messenger->Printers();
    for (int i = 1; i <= printers.Size(); i++) {
        Handle(Message_PrinterOStream) const osp =
            Handle(Message_PrinterOStream)::DownCast(printers.Value(i));
        if (!osp.IsNull()) {
            // Nulify the private myStream field so Close() returns immediately.
            // Layout: vtable(8) + refcount(4) + myTraceLevel(4) + myStream(8) ...
            *reinterpret_cast<void**>(reinterpret_cast<char*>(osp.get()) + 16) = nullptr;
        }
    }

    messenger->ChangePrinters().Clear();
}

void gdext_initialize_module(godot::ModuleInitializationLevel p_level) {
    if (p_level != godot::MODULE_INITIALIZATION_LEVEL_SCENE) {
        return;
    }

    // Register all discovered wrapper classes
    GDREGISTER_CLASS(Axis);
    GDREGISTER_CLASS(CadPlane);
    GDREGISTER_CLASS(GeometryVector);
    GDREGISTER_CLASS(Location);
    GDREGISTER_CLASS(OpenCascadeVersion);
    GDREGISTER_CLASS(ShapeList);
    GDREGISTER_CLASS(TopoShape);
    GDREGISTER_CLASS(Vertex);
    GDREGISTER_CLASS(Wire);
    GDREGISTER_CLASS(CircleWire);
    GDREGISTER_CLASS(Compound);
    GDREGISTER_CLASS(Edge);
    GDREGISTER_CLASS(EllipseWire);
    GDREGISTER_CLASS(Face);
    GDREGISTER_CLASS(PolygonWire);
    GDREGISTER_CLASS(RectangleRoundedWire);
    GDREGISTER_CLASS(RectangleWire);
    GDREGISTER_CLASS(RegularPolygonWire);
    GDREGISTER_CLASS(Shell);
    GDREGISTER_CLASS(SlotOverallWire);
    GDREGISTER_CLASS(Solid);
    GDREGISTER_CLASS(SolidTorus);
    GDREGISTER_CLASS(SolidWedge);
    GDREGISTER_CLASS(SolidBox);
    GDREGISTER_CLASS(SolidCone);
    GDREGISTER_CLASS(SolidCylinder);
    GDREGISTER_CLASS(SolidSphere);
    clear_messenger_printers();
}

void gdext_uninitialize_module(godot::ModuleInitializationLevel p_level) {
    if (p_level != godot::MODULE_INITIALIZATION_LEVEL_SCENE) {
        return;
    }
    clear_messenger_printers();
}

extern "C" {
    auto GDE_EXPORT gdext_library_init(
        GDExtensionInterfaceGetProcAddress p_get_proc_address,
        GDExtensionClassLibraryPtr p_library,
        GDExtensionInitialization *r_initialization
    ) -> GDExtensionBool {
        godot::GDExtensionBinding::InitObject const init_obj(
            p_get_proc_address, p_library, r_initialization
        );

        init_obj.register_initializer(gdext_initialize_module);
        init_obj.register_terminator(gdext_uninitialize_module);
        init_obj.set_minimum_library_initialization_level(godot::MODULE_INITIALIZATION_LEVEL_SCENE);

        return init_obj.init();
    }
}
